// <auto-generated />
using System;
using Backend.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260110050342_DurationResultMigration")]
    partial class DurationResultMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryName")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = 3
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = 2
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = 4
                        });
                });

            modelBuilder.Entity("Backend.Models.Choices", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChoiceText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Choice");
                });

            modelBuilder.Entity("Backend.Models.Paragraphs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ParagraphText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Paragraph");
                });

            modelBuilder.Entity("Backend.Models.Questions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ParagraphId")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("YearPeriodId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParagraphId");

                    b.HasIndex("SubCategoryId");

                    b.HasIndex("YearPeriodId");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("Backend.Models.Results", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPassed")
                        .HasColumnType("boolean");

                    b.Property<int>("TotalScore")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("duration")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Result");
                });

            modelBuilder.Entity("Backend.Models.SubCategories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("SubCategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            SubCategoryName = "Nouns"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            SubCategoryName = "Gender"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            SubCategoryName = "Grammatical Number"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            SubCategoryName = "Verbs"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            SubCategoryName = "Tenses"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            SubCategoryName = "Pronouns"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            SubCategoryName = "Adjectives"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            SubCategoryName = "Adverbs"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            SubCategoryName = "Prepositions"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            SubCategoryName = "Conjunctions"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            SubCategoryName = "Interjections"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            SubCategoryName = "Articles"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            SubCategoryName = "Subject-Verb Agreement"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            SubCategoryName = "Sentence Construction"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            SubCategoryName = "Sentence Structure"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            SubCategoryName = "Affixes"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 1,
                            SubCategoryName = "Punctuations"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            SubCategoryName = "Correct Usage"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            SubCategoryName = "Error Identification"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            SubCategoryName = "Synonyms"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 1,
                            SubCategoryName = "Antonyms"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 1,
                            SubCategoryName = "Analogy"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 1,
                            SubCategoryName = "Paragraph Organization"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 1,
                            SubCategoryName = "Reading Comprehension"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 2,
                            SubCategoryName = "Logical Reasoning"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 2,
                            SubCategoryName = "Flowchart"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 2,
                            SubCategoryName = "Problem Solving"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 2,
                            SubCategoryName = "Special Topic"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 2,
                            SubCategoryName = "Cognitive Reasoning"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 3,
                            SubCategoryName = "Vocabulary and Spelling"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 3,
                            SubCategoryName = "Alphabetizing"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 4,
                            SubCategoryName = "Divisibility Rules"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 4,
                            SubCategoryName = "Multiples and Factors"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 4,
                            SubCategoryName = "Integers"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 4,
                            SubCategoryName = "PEMDAS"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 4,
                            SubCategoryName = "Decimals"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 4,
                            SubCategoryName = "Fractions"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 4,
                            SubCategoryName = "Operations on Fractions"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 4,
                            SubCategoryName = "Percent"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 4,
                            SubCategoryName = "Ratio and Proportion"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 4,
                            SubCategoryName = "Averages"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 4,
                            SubCategoryName = "Tables, Charts, and Graphs"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 4,
                            SubCategoryName = "Linear Equations"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 4,
                            SubCategoryName = "Solving Mathematical Expressions"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 4,
                            SubCategoryName = "Writing Mathematical Expressions"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 4,
                            SubCategoryName = "Word Problem Techniques"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 4,
                            SubCategoryName = "Number Problems"
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 4,
                            SubCategoryName = "Odd, Even, and Consecutive Integers"
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 4,
                            SubCategoryName = "Age Problems"
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 4,
                            SubCategoryName = "Work Problems"
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 4,
                            SubCategoryName = "Geometry Problems"
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 5,
                            SubCategoryName = "The 1987 Constitution"
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 5,
                            SubCategoryName = "Republic Act No. 6713"
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 5,
                            SubCategoryName = "Peace and Human Rights Issues and Concepts"
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 5,
                            SubCategoryName = "Environmental Management and Protection"
                        });
                });

            modelBuilder.Entity("Backend.Models.UserAnswers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Answer")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<int?>("QuestionsNavigationId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Answer");

                    b.HasIndex("QuestionsNavigationId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAnswer");
                });

            modelBuilder.Entity("Backend.Models.Users", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Backend.Models.YearPeriods", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Periods")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("YearPeriod");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Choices", b =>
                {
                    b.HasOne("Backend.Models.Questions", "QuestionsNavigation")
                        .WithMany("ChoicesCollection")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionsNavigation");
                });

            modelBuilder.Entity("Backend.Models.Questions", b =>
                {
                    b.HasOne("Backend.Models.Paragraphs", "ParagraphNavigation")
                        .WithMany("QuestionsCollection")
                        .HasForeignKey("ParagraphId");

                    b.HasOne("Backend.Models.SubCategories", "SubCategoryNavigation")
                        .WithMany("QuestionsCollection")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.YearPeriods", "YearPeriodNavigation")
                        .WithMany("QuestionsCollection")
                        .HasForeignKey("YearPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParagraphNavigation");

                    b.Navigation("SubCategoryNavigation");

                    b.Navigation("YearPeriodNavigation");
                });

            modelBuilder.Entity("Backend.Models.Results", b =>
                {
                    b.HasOne("Backend.Models.Users", "UsersNavigation")
                        .WithMany("ResultsCollection")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsersNavigation");
                });

            modelBuilder.Entity("Backend.Models.SubCategories", b =>
                {
                    b.HasOne("Backend.Models.Category", "categoryNavigation")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categoryNavigation");
                });

            modelBuilder.Entity("Backend.Models.UserAnswers", b =>
                {
                    b.HasOne("Backend.Models.Choices", "ChoicesNavigation")
                        .WithMany("UserAnswersCollection")
                        .HasForeignKey("Answer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Questions", "QuestionsNavigation")
                        .WithMany("AnswersCollection")
                        .HasForeignKey("QuestionsNavigationId");

                    b.HasOne("Backend.Models.Users", "UserNavigation")
                        .WithMany("UserAnswersCollection")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChoicesNavigation");

                    b.Navigation("QuestionsNavigation");

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Backend.Models.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Backend.Models.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Backend.Models.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Models.Category", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Backend.Models.Choices", b =>
                {
                    b.Navigation("UserAnswersCollection");
                });

            modelBuilder.Entity("Backend.Models.Paragraphs", b =>
                {
                    b.Navigation("QuestionsCollection");
                });

            modelBuilder.Entity("Backend.Models.Questions", b =>
                {
                    b.Navigation("AnswersCollection");

                    b.Navigation("ChoicesCollection");
                });

            modelBuilder.Entity("Backend.Models.SubCategories", b =>
                {
                    b.Navigation("QuestionsCollection");
                });

            modelBuilder.Entity("Backend.Models.Users", b =>
                {
                    b.Navigation("ResultsCollection");

                    b.Navigation("UserAnswersCollection");
                });

            modelBuilder.Entity("Backend.Models.YearPeriods", b =>
                {
                    b.Navigation("QuestionsCollection");
                });
#pragma warning restore 612, 618
        }
    }
}
